name: Deploy # 工作流的名称

on: # 定义触发工作流的事件
  push:
    branches:
      - main # 当推送代码到 main 分支时触发工作流

jobs:
  deploy: # 定义一个名为 deploy 的任务
    runs-on: ubuntu-latest # 指定运行任务的操作系统环境
    name: Deploy # 任务的名称

    steps:
      - name: Checkout code # 检出代码
        uses: actions/checkout@v4

      - name: Deploy app # 部署应用
        uses: cloudflare/wrangler-action@v3 # 使用 cloudflare/wrangler-action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} 
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # Cloudflare 账户 ID，从 GitHub Secrets 获取
          command: pages deploy ./dist --project-name=vanilla-chat-demo-tmpl # 指定部署 Pages 应用的命令
