name: Deploy # 工作流的名称

# 删除 push 事件触发器，改为手动触发
on:
  workflow_dispatch: # 手动触发 workflow 的事件
    inputs:
      environment:
        description: "选择要部署的环境：<dev|staging|prod>"
        required: true
        default: "dev"

jobs:
  deploy: # 定义一个名为 deploy 的任务
    runs-on: ubuntu-latest # 指定运行任务的操作系统环境
    name: Deploy # 任务的名称

    steps:
      - name: Checkout code # 检出代码
        uses: actions/checkout@v4

      - name: Install dependencies # 安装项目依赖
        run: npm install

      - name: Build # 构建项目
        run: npm run build

      - name: Deploy app # 部署应用
        uses: cloudflare/wrangler-action@v3 # 使用 cloudflare/wrangler-action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # Cloudflare API 令牌，从 GitHub Secrets 获取
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # Cloudflare 账户 ID，从 GitHub Secrets 获取
          command: pages deploy ./dist --project-name=vanilla-chat-demo-tmpl # 指定部署 Pages 应用的命令
